### ISSUE TITLE
Alerta (Warning) no script sip_instalar_modulo_pesquisa.php 

### ISSUE THREAD

**Issue by tadeubas** [cadegovbr/mod-sei-pesquisa-SEI#17]
Prezados, bom dia

Estamos usando o SEI 3.1.5 com o módulo de pesquisa pública 3.0.6.
Ao executar o script `/opt/sip/scripts/sip_instalar_modulo_pesquisa.php` obtenho um alerta na `linha 00004`, porém o script termina a execução corretamente. Isso é algo que eu deveria me preocupar?

```
00001 -  SIP - INICIALIZAR 
00002 - [InfraRN->__call] AtualizadorSipModuloPesquisaRN.atualizarVersao
00003 - [InfraMySqli->abrirConexao] InfraMySqli-mysql-3306-sip-sip_user
00004 - [Infra->infraGerarExcecao] 10: Warning: /opt/sip/scripts/sip_instalar_modulo_pesquisa.php linha:33.
ini_set(): Cannot change zlib.output_compression - headers already sent

00001 - INICIANDO ATUALIZACAO DO MODULO DE PESQUISA NO SIP VERSAO 2.1.6

...

00013 - [InfraMySqli->consultarSql] SELECT infra_parametro.valor FROM infra_parametro WHERE infra_parametro.nome='VERSAO_MODULO_PESQUISA_PUBLICA'
00014 - [InfraMySqli->consultarSql] 0 s
00015 - SIP - M�DULO PESQUISA P�BLICA v3.0.0 J� INSTALADO
00016 - TEMPO TOTAL DE EXECU��O: 0.029 s
00017 - FIM
```

No `PHP_INFO()` aparece assim:

![image](https://user-images.githubusercontent.com/5518496/156579550-679490a9-e870-4519-ac38-07a336fa09a0.png)

**Comment by neijobson** [comment]
Não precisa se preocupar com esse alerta dado no meio do script do SIP. Não tinha utilidade esse acionamento do zlib.output_compression no script.

No script do SIP do módulo para o SEI 4.0, inclusive, o instanciamento do zlib.output_compression foi retirado.
