### ISSUE TITLE
Erro no script sip_atualizar_versao_modulo_pesquisa - v4.0.0

### ISSUE THREAD

**Issue by marcusliborio** [cadegovbr/mod-sei-pesquisa-SEI#3]
Boa tarde!

Ao executar o script "sip_atualizar_versao_modulo_pesquisa" foi gerado o seguinte erro:

ini_set(): Cannot change zlib.output_compression - headers already sent

[ERRO - atualizacao_modulo_pesquisa_sip_v4.0.0.log](https://github.com/cadegovbr/mod-sei-pesquisa-SEI/files/6832570/ERRO.-.atualizacao_modulo_pesquisa_sip_v4.0.0.log)

Atenciosamente,

**Comment by eliasjrvip** [comment]
Prezados,

Também estou com o mesmo erro. 

Atenciosamente.

**Comment by neijobson** [comment]
@marcusliborio e @eliasjrvip
Problema resolvido nos scripts e a Release v4.0.0 foi gerada novamente: https://github.com/cadegovbr/mod-sei-pesquisa-SEI/releases/tag/v4.0.0

Basta baixar novamente, sobrescrever e executar os procedimentos do README mais uma vez.

Atenção para não ter mais nos arquivos ConfiguracaoSEI e ConfiguracaoSip as chaves de UsuarioScript e SenhaScript.
Os scripts do Pesquisa estava criticando isso, mas não devem mais existir, devendo informar o usuário de banco com permissão de DDL e sua senha em linha de comando no momento da execução dos scripts do SEI e do SIP do módulo.
